// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cpwxeodtvbhymrclvvjc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNwd3hlb2R0dmJoeW1yY2x2dmpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk1NzU3ODgsImV4cCI6MjA1NTE1MTc4OH0.v9AED4ddaDx_PA26Cjy7KdvWvhDfnEmYIW5NLKNJJXE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);